#!/bin/bash
cd /Users/ahtavarasmus/cp/ 
source venv/bin/activate 
python3 paste_to_input.py 
sleep 1
var=$(</Users/ahtavarasmus/cp/problems/tmp.txt)
cd /Users/ahtavarasmus/cp/problems/
cd $var
nvim problem.cpp

